<?php

namespace App\HttpController\Index;

use App\Base\HomeBaseController;
use EasySwoole\Core\Http\Request;
use EasySwoole\Core\Http\Response;
use think\Db;

/**
 * Class Index
 * @package App\HttpController
 */
class Index extends HomeBaseController
{
    public function __construct(string $actionName, Request $request, Response $response)
    {
        parent::__construct($actionName, $request, $response);
    }

    protected function onRequest($action): ?bool
    {
        return parent::onRequest($action); // TODO: Change the autogenerated stub
    }
    // 首页重定向到前端页面
    public function index()
    {
        $current_url = ['current_url' => 'http://68dj.cn',];
        $this->getView()->assign($current_url);
        $this->fetch('index');
    }
    // 首页参数json
    public function home(){
        $sysinfo = Db::name('system')->where('name','home_config')->value('value');
        $sysinfo = unserialize($sysinfo);
        $version = Db::query('SELECT VERSION() AS ver');
        $config  = [
            'url'             => $_SERVER['HTTP_HOST'],
            'document_root'   => $_SERVER['DOCUMENT_ROOT'],
            'server_os'       => PHP_OS,
            'server_port'     => $_SERVER['SERVER_PORT'],
            'server_soft'     => $_SERVER['SERVER_SOFTWARE'],
            'php_version'     => PHP_VERSION,
            'mysql_version'   => $version[0]['ver'],
            'max_upload_size' => ini_get('upload_max_filesize')];
        $home_data = [
            'code' => 1,
            'sysinfo' => $sysinfo,
            'config' => $config
        ];
        $this->response()->withHeader('Content-type','application/json;charset=utf-8');
        $this->response()->write(json_encode($home_data));
    }

    //


    // json 请求模板
    public function json(){
        $sysinfo = Db::name('system')->where('id',2)->select();
        $this->response()->withHeader('Content-type','application/json;charset=utf-8');
        $this->response()->write(json_encode($sysinfo));
    }
    // ----------------------  测试脚本 -------------------//
    public function hello(){
        echo  '从服务器获取wx 和 cookie';
        $result = Db::name('wxurlcookie')->field('id,cookie,status,username,wxhead')->where('status', 1)->select();
//         var_dump($result);
        $assign = array(
            'result'=>$result
        );
        $this->getView()->assign($assign);
        $this->fetch('hello');
    }
    
    public function index1()
    {
        $sql = "show tables";
        $re = Db::query($sql);
//        var_dump($re);
        $assign = array(
            'test'=>1,
            'db'=>$re
        );
        $this->getView()->assign($assign);
        $this->fetch('index');
    
    }

    public function test(){
        $this->session()->set('user',array('nickname'=>'仙士可123','name'=>'tioncico123'));
    }

}

