<?php
/**
 * Created by PhpStorm.
 * User: x
 * Date: 2019/1/8
 * Time: 15:04
 */
namespace  App\HttpController\Api;

use App\Base\HomeBaseController;
use EasySwoole\Core\Http\Request;
use EasySwoole\Core\Http\Response;
use think\Db;
/*
 * 广告统计系统使用
 * */
class Ad extends HomeBaseController
{
    public function __construct(string $actionName, Request $request, Response $response)
    {
        parent::__construct($actionName, $request, $response);
    }

    protected function onRequest($action): ?bool
    {
        return parent::onRequest($action); // TODO: Change the autogenerated stub
    }

    //模板消息跳转API
    public function manyurls(){
        $request = $this->request();
        $id = $request->getRequestParam('id');
        $url_postfix = Db::name('wxurls')->field('postfix,pid,domain')->where('id',$id)->select();
        $url_postfix = $url_postfix[0];
        $this->response()->withHeader('Content-type','application/json;charset=utf-8');
        if($url_postfix){
            // 选出随机的二跳域名domain
            $map = [ 'status' => 1 ,
                'type'   => 2 ,
                'pid'   => $url_postfix['pid']  ];
            $url_domain = Db::name('wxurls')->query('SELECT domain, id  FROM think_wxurls WHERE `status` = 1 AND type = 2 AND pid = '.$url_postfix['pid'].' ORDER BY RAND() LIMIT 1');
            if($url_domain){
                Db::name('wxurls')->query('UPDATE think_wxurls set jump_reads=jump_reads+1 WHERE id =' . $url_domain[0]['id']);
                // 增加一次的访问量  update student set score=score+1 where id = 1
                Db::name('wxurls')->query('UPDATE think_wxurls set jump_reads=jump_reads+1 WHERE id = ' . $id);
                $url_domain = $url_domain[0]['domain'];
                $domain = $url_domain.'/'.$url_postfix['postfix'] .'/index.html' ;
                $this->response()->write(json_encode(['status' => 1, 'url' => $domain]));
            }else{
                $this->response()->write(json_encode(['status' => 2, 'url' => $url_postfix['domain'].'/'.$url_postfix['postfix'].'/index.html']));
            }
        }else{
            $this->response()->write(json_encode(['status' => 3, 'msg' => 'ID is not here!']));
        }
    }



}